# Generated by Django 5.2.11 on 2026-02-28 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('section1', models.TextField(blank=True, verbose_name='Panel 1')),
                ('section2', models.TextField(blank=True, verbose_name='Panel 2')),
                ('section3', models.TextField(blank=True, verbose_name='Panel 3')),
                ('section4', models.TextField(blank=True, verbose_name='Panel 4')),
                ('section5', models.TextField(blank=True, verbose_name='Panel 5')),
                ('section6', models.TextField(blank=True, verbose_name='Panel 6')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'bulletin',
                'verbose_name_plural': 'bulletins',
                'ordering': ['-date'],
            },
        ),
    ]
