# Generated by Django 5.2.11 on 2026-03-17 11:43

import sermons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('youtube_id', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=sermons.models.handle_upload)),
                ('published_date', models.DateTimeField()),
                ('access', models.CharField(choices=[('anyone', 'Anyone'), ('email', 'Email Required')], default='anyone', max_length=20)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('scheduled', 'Scheduled')], default='draft', max_length=20)),
            ],
        ),
    ]
