# Generated by Django 5.2.11 on 2026-03-17 14:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sermon',
            old_name='published_date',
            new_name='published_at',
        ),
        migrations.RemoveField(
            model_name='sermon',
            name='image',
        ),
        migrations.AddField(
            model_name='sermon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sermon',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sermon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='youtube_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
