# Generated by Django 5.2.11 on 2026-03-17 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0002_rename_published_date_sermon_published_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sermon',
            options={'ordering': ['-published_at']},
        ),
    ]
