# Generated by Django 5.2.11 on 2026-03-19 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0006_series_sermon_series_delete_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sermon',
            name='thumbnail_url',
        ),
    ]
