# Generated by Django 5.2.11 on 2026-03-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0007_remove_sermon_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
