# Generated by Django 5.2.11 on 2026-03-23 10:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0008_alter_sermon_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
