# Generated by Django 5.2.11 on 2026-03-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0009_series_created_at_series_published_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='youtube_playlist_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='youtube_id',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
