# Generated by Django 5.2.11 on 2026-03-25 12:30

import sermons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0010_alter_series_youtube_playlist_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='series',
            field=models.ForeignKey(on_delete=models.SET(sermons.models.get_standalone_series), related_name='sermons', to='sermons.series'),
        ),
    ]
