# Generated by Django 5.2.11 on 2026-03-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0011_series_slug_alter_sermon_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
