# Generated by Django 5.2.11 on 2026-04-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0012_alter_series_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
