# Generated by Django 5.2.11 on 2026-02-25 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Display name in the navbar (e.g. 'About Us', 'Services')", max_length=100)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from title — used in URLs if needed', max_length=120, unique=True)),
                ('url_or_path', models.CharField(blank=True, help_text="Full URL[](https://...) or Django named path (e.g. 'blog:post-list')", max_length=255, verbose_name='URL or path')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_visible', models.BooleanField(default=True, help_text='Uncheck to hide without deleting', verbose_name='Show in navigation?')),
                ('css_class', models.CharField(blank=True, help_text="Extra CSS class (e.g. 'dropdown', 'highlight', 'new-badge')", max_length=100)),
                ('icon', models.CharField(blank=True, help_text="Font Awesome / Heroicon name, e.g. 'fa-solid fa-house'", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Leave empty for top-level menu items', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Locations.location', verbose_name='Parent location')),
            ],
            options={
                'verbose_name': 'Navigation Location',
                'verbose_name_plural': 'Navigation Locations',
                'ordering': ['order', 'title'],
            },
        ),
    ]
