# Generated by Django 5.2.11 on 2026-03-06 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0003_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Locations.address'),
        ),
    ]
