# Generated by Django 5.2.11 on 2026-03-06 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0004_location_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='Locations/photos/'),
        ),
    ]
