# Generated by Django 5.2.11 on 2026-03-08 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0005_location_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
    ]
