# Generated by Django 5.2.11 on 2026-03-08 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0006_alter_location_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='css_class',
        ),
        migrations.RemoveField(
            model_name='location',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='location',
            name='url_or_path',
        ),
        migrations.CreateModel(
            name='ServiceTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('sun', 'Sunday'), ('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday')], default='sun', max_length=3)),
                ('time', models.TimeField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='Locations.location')),
            ],
            options={
                'ordering': ['day', 'order', 'time'],
            },
        ),
    ]
