# Generated by Django 5.2.11 on 2026-03-01 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_pages', '0002_landingpageentry_active_landingpageentry_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpageentry',
            name='slug',
        ),
    ]
