# Generated by Django 5.2.11 on 2026-02-27 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='parent',
        ),
    ]
