# Generated by Django 5.2.11 on 2026-02-27 22:01

import staff.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='email',
            field=models.EmailField(blank=True, max_length=254, validators=[staff.validators.validate_blocked_email]),
        ),
    ]
